// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8tbrQXr3uMjOIEZPeD_wwhfbtBUsOyg',
    appId: '1:645073564276:web:4c69aaf272f4f7a1441721',
    messagingSenderId: '645073564276',
    projectId: 'calendarapp-596b3',
    authDomain: 'calendarapp-596b3.firebaseapp.com',
    storageBucket: 'calendarapp-596b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxD8wLCccdD7ofzin6eQMSKcPbbGSFlY',
    appId: '1:645073564276:android:28630200c0762985441721',
    messagingSenderId: '645073564276',
    projectId: 'calendarapp-596b3',
    storageBucket: 'calendarapp-596b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCohVrExXS88rlxenc24rBsliyGySSpz6E',
    appId: '1:645073564276:ios:d4844c5f98fa7560441721',
    messagingSenderId: '645073564276',
    projectId: 'calendarapp-596b3',
    storageBucket: 'calendarapp-596b3.appspot.com',
    iosClientId: '645073564276-4lfpln0uajmscoj2oiao7m7skk8orbhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.khoaLuan1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCohVrExXS88rlxenc24rBsliyGySSpz6E',
    appId: '1:645073564276:ios:d4844c5f98fa7560441721',
    messagingSenderId: '645073564276',
    projectId: 'calendarapp-596b3',
    storageBucket: 'calendarapp-596b3.appspot.com',
    iosClientId: '645073564276-4lfpln0uajmscoj2oiao7m7skk8orbhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.khoaLuan1',
  );
}
